CREATE TABLE Klient(
ID INTEGER(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
email TEXT(255) NULL,
passwod TEXT(255) NULL,
nimi TEXT(255) NULL,
per_nimi TEXT(255) NULL,
adress TEXT(255) NULL,
telefon INTEGER(10) NULL,
role ENUM('user','admin')NULL,
InfoID TEXT (255) NULL
)ENGINE=InnoDB;




CREATE TABLE Info(
ID INTEGER(3) NOT NULL AUTO_INCREMENT PRIMARY KEY,
InfoID TEXT(255) NULL,
InfoCategory ENUM('tulud','kulud')NULL,
InfoNimi TEXT(255) NULL,
EeldatavSumm INTEGER NULL,
TegelikSumm INTEGER NULL
)ENGINE=InnoDB;






ALTER TABLE Klient ADD CONSTRAINT inf_id FOREIGN KEY (InfoID) REFERENCES Info (InfoID);


